# Generated by Django 3.2.3 on 2021-06-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaceData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('racer_id', models.IntegerField()),
                ('team_id', models.IntegerField()),
                ('timestamp', models.IntegerField()),
                ('races', models.IntegerField()),
                ('time', models.IntegerField()),
                ('typed', models.IntegerField()),
                ('errs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RacerData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('racer_id', models.IntegerField()),
                ('timestamp', models.IntegerField()),
                ('join_stamp', models.IntegerField()),
                ('last_activity', models.IntegerField()),
                ('last_login', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RacerLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('racer_id', models.IntegerField()),
                ('team_id', models.IntegerField()),
                ('timestamp', models.IntegerField()),
                ('role', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=100)),
                ('total_races', models.IntegerField()),
                ('speed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('team_id', models.IntegerField()),
                ('timestamp', models.IntegerField()),
                ('tag', models.CharField(max_length=10)),
                ('tag_color', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
