# Generated by Django 3.2.3 on 2021-06-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdata',
            name='tag_color',
            field=models.CharField(default='ea1979', max_length=10),
            preserve_default=False,
        ),
    ]
