# Generated by Django 3.2.3 on 2021-06-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racerlog',
            name='role',
        ),
        migrations.AddField(
            model_name='racerdata',
            name='role',
            field=models.CharField(default='member', max_length=10),
            preserve_default=False,
        ),
    ]
