# Generated by Django 3.2.3 on 2021-06-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210612_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='racerdata',
            name='team_id',
            field=models.IntegerField(default=765879),
            preserve_default=False,
        ),
    ]
